name: Test Blazor WebAssembly

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: feature/demo-live

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor WebAssembly
        run: dotnet publish WebSite/WebSite.Client/WebApp.csproj -c Release -o publish

      - name: Prepare GitHub Pages files
        run: |
          touch publish/wwwroot/.nojekyll
          cp publish/wwwroot/index.html publish/wwwroot/404.html

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: blazor-site
          path: ./publish/wwwroot
