<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>3.0.0</Version>
    <Title>BlazorGraphs</Title>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>blazor; dotnet; gauges; charts; blazor-charts; data-visualization; svg; no-js</PackageTags>
    <PackageIcon>ICON.png</PackageIcon>
    <Authors>Edoardo Paris;</Authors>
	  <PackageProjectUrl>https://www.BlazorGraphs.it</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/EdoParis/BlazorCharts</RepositoryUrl>
	  <RepositoryType>git</RepositoryType>
    <Description>Lightweight library to draw .svg charts and gauges for Blazor (No Javascript)</Description>
    <PackageReleaseNotes>
		- Added Stepline chart
		- Added Scatter chart
		- Added Bubbles chart
		- Improved color choices
		- Refactored Line chart 
		- Reduced namespaces
		- Renamed some components
		- Removed obsolete components
		- Removed enums
	</PackageReleaseNotes>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.19" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\ICON.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
